### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by easella** [QuiteAFancyEmerald/Holy-Unblocker#107]
my school uses contentkeeper and all the links were blocked before i even got them
damage.gq
catsarecool.design
holyubofficial.net
holyubofficial.ml
cycle.ga
damage.gq
transparent.gq
beachball.xyz
referencefile.org
grammarfiles.net
catcoup.xyz
degreefinder.cf
https://precede.design/
https://www.thermomap.xyz/
https://x-ray-edu.gq/
deepsoil.ml
https://flexibleedu.gq/
thermomap.xyz

those are all the ones i tried, and all were blocked

**Comment by QuiteAFancyEmerald** [comment]
#44 
Plus I emailed you a working site awhile back....

**Comment by easella** [comment]
please provide me one thats not blocked by contentkeeper!
![image](https://user-images.githubusercontent.com/74786054/117675411-888cfe00-b17a-11eb-9918-8ec0289da378.png)
![image](https://user-images.githubusercontent.com/74786054/117675429-8d51b200-b17a-11eb-899f-03424e4250e8.png)
![image](https://user-images.githubusercontent.com/74786054/117675450-92aefc80-b17a-11eb-8e97-5db38e54fdce.png)
![image](https://user-images.githubusercontent.com/74786054/117675467-96428380-b17a-11eb-8245-b70fe688f371.png)
![image](https://user-images.githubusercontent.com/74786054/117675495-9cd0fb00-b17a-11eb-8fb1-fad35812824e.png)
![image](https://user-images.githubusercontent.com/74786054/117675507-a0fd1880-b17a-11eb-8c67-1b7e3b22bac0.png)
![image](https://user-images.githubusercontent.com/74786054/117675532-a65a6300-b17a-11eb-80fa-7281aa137b70.png)
![image](https://user-images.githubusercontent.com/74786054/117675560-aa868080-b17a-11eb-8055-8c87b9d6ef0c.png)

**Comment by QuiteAFancyEmerald** [comment]
Check your spam folder or something idk

**Comment by easella** [comment]
send it again

**Comment by QuiteAFancyEmerald** [comment]
alright

**Comment by easella** [comment]
its blocked
![image](https://user-images.githubusercontent.com/74786054/117731623-72a02d00-b1bc-11eb-9562-dc0831c1a9c0.png)
