### ISSUE TITLE
Cant solve the discord captcha

### ISSUE THREAD

**Issue by sufficients** [QuiteAFancyEmerald/Holy-Unblocker#117]
Hello, I tried to login to my account using the womginx proxy but instead of logging me in, it presented me a **quite broken** captcha. Any help would be appreciated as this is not the first time this has locked me out of my account.
![A8F3ED49-2857-482A-AA28-B82C3E702CBE](https://user-images.githubusercontent.com/75097279/117849767-a5950000-b252-11eb-8c70-fce355fff9e5.jpeg)

**Comment by sufficients** [comment]
Oh nevermind, it just fixed itself. Sorry!

**Comment by QuiteAFancyEmerald** [comment]
Yeah Womginx can be rather glitchy sometimes so it takes a few attempts.
