### ISSUE TITLE
cant join discord

### ISSUE THREAD

**Issue by easella** [QuiteAFancyEmerald/Holy-Unblocker#118]
i dont have a phone
why dont you simply list all the holyunblocker links down! please!

**Comment by sufficients** [comment]
If he lists all of the holyunblocker links, they will get blocked quickly.

**Comment by SkidFace** [comment]
Easella you can use a PC for this lol

**Comment by easella** [comment]
i have kaspersky safe kids on my pc!  And its impossible to bypass(not even the alloyproxy works)

**Comment by easella** [comment]
i want you 2! At least send them to my email! PLEASEEEEE!

**Comment by QuiteAFancyEmerald** [comment]
Check your email. If you open more issues here regarding this you will be blacklisted from this repository.

Will leave this open for your response confirming you got the email.

**Comment by easella** [comment]
blocked
![image](https://user-images.githubusercontent.com/74786054/118139534-74910880-b3d5-11eb-97b5-1b673abdd582.png)

**Comment by QuiteAFancyEmerald** [comment]
Alright check again now.

**Comment by easella** [comment]
thank you!
![image](https://user-images.githubusercontent.com/74786054/118154626-487d8380-b3e5-11eb-88f0-ea421f8bf887.png)

**Comment by QuiteAFancyEmerald** [comment]
Of course no problem! :D
(try not to leak that site please)

**Comment by easella** [comment]
ok i wont
