### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by easella** [QuiteAFancyEmerald/Holy-Unblocker#121]
![image](https://user-images.githubusercontent.com/74786054/118157753-f179ad80-b3e8-11eb-8ac9-b79e73401095.png)
please fix this i have an unblocked games site and i wanna add wings io but i cant so please fix it

**Comment by QuiteAFancyEmerald** [comment]
![image](https://user-images.githubusercontent.com/46467239/118158100-35ac8400-b3d0-11eb-884c-755e7e3db5a2.png)

**Comment by easella** [comment]
please fix
