### ISSUE TITLE
How do I just get to the website on a school chromebook

### ISSUE THREAD

**Issue by sdkhfgvwierg** [QuiteAFancyEmerald/Holy-Unblocker#380]

**Comment by windowmandav** [comment]
you need a url that is not blocked by the school

**Comment by Gitry305** [comment]
can someone get a unblocked version of this, or can i use a URL scrambler

**Comment by QuiteAFancyEmerald** [comment]
You would have to join the TN discord and use the proxy bot to obtain another site. Check out the README.

**Comment by Bendylol666** [comment]
How about read me
