### ISSUE TITLE
(this is a question, not an issue)

### ISSUE THREAD

**Issue by easella** [QuiteAFancyEmerald/Holy-Unblocker#70]
can you please deploy your own to heroku and make it so all the externally hosted proxies work?
I do not know ho to use cloudflare and even if I did it would be blocked by content keeper.
heroku is unblocked though. I do not want to pay so I can use custom domains so please.

**Comment by Pers0n-dev** [comment]
@easella here https://sourpotato.herokuapp.com it has system ya

**Comment by easella** [comment]
no it does not.
![image](https://user-images.githubusercontent.com/74786054/115130741-fdc44380-9fbf-11eb-97eb-5df21d73548d.png)

**Comment by easella** [comment]
hey and by the way do you want me to add any more games to my website?
Oh yeah and if your school blocks it [click here](https://additionpractice.glitch.me)

**Comment by QuiteAFancyEmerald** [comment]
And you can't join the TN Discord at all? You can easily obtain more Holy Unblocker links without having to host anything yourself, while being unblocked.

**Comment by easella** [comment]
can you please tell me all the holy unblocked links?

**Comment by QuiteAFancyEmerald** [comment]
Have you tried deploying your own Womginx instance to Heroku? You could log in normally with it and perhaps join the TN Discord that way.

**Comment by easella** [comment]
yeah

**Comment by easella** [comment]
yeah and by the way can you deploy a working systemya to heroku? please?

**Comment by MrMachi9** [comment]
hi

**Comment by easella** [comment]
hey MrMachi9 what web filter does your school use?

**Comment by easella** [comment]
hey everyone try my unblocked games site:[click here](https://additionpractice.glitch.me)

**Comment by MrMachi9** [comment]
omg you might have just helped me with some thing big

**Comment by MrMachi9** [comment]
you know what https://flexibleedu.gq/ here you go

**Comment by MrMachi9** [comment]
thats a holy unblocker site

**Comment by Pers0n-dev** [comment]
grem.ml

**Comment by easella** [comment]
its blocked

**Comment by easella** [comment]
both are blocked

**Comment by easella** [comment]
did you guys try my games site?

**Comment by Pers0n-dev** [comment]
yes

**Comment by easella** [comment]
Do you like it? Do you want me to add any more games? Are all the games unblocked?

**Comment by easella** [comment]
hey MrMachi9 did you try my games site?

**Comment by QuiteAFancyEmerald** [comment]
Just why... don't advertise here.... D:
